accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"

urlpatterns = [
 path('register/', views.register_page, name="register"),
 path('login/', views.login_page, name="login"),
 path('logout/', views.logout_page, name="logout")
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.http import HttpResponseRedirect
from django.contrib.auth import login, logout


def register_page(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return HttpResponseRedirect("/")

            # if the request is a post request that meets validation then save users data.
    else:  # this means it is a GET request.
        form = UserCreationForm()
    return render(request, "accounts/register.html", {'form': form})


def login_page(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return HttpResponseRedirect("/")
            # login in the user
    else:
        form = AuthenticationForm()

    return render(request, "accounts/login.html", {'form': form})


def logout_page(request):
    if request.method == "POST":
        logout(request)
        return HttpResponseRedirect("/")

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}
{% load static %}

{% block content %}
  <title>Login</title>


  <link rel="stylesheet" href="{% static 'accounts/login-page.css' %}">


  <section class="hero2">

    <div class="site-description">
      <h2>Login to your gadget master account</h2>
      <br>
      <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
          <div class="fieldWrapper">
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
          </div>
        {% endfor %}
        <br>
        <button class="btn-login-auth" type="submit"><span>Login</span></button>
      </form>
      <p>Created by 0701CODER</p>
    </div>
  </section>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base_layout.html' %}
{% load static %}


{% block content %}
<title>Register</title>
<link rel="stylesheet" href="{% static 'accounts/register-page.css' %}">
<section class="hero3">
  <div class="site-description-register">
    <h2>Register with GADGET MASTER</h2>
    <br>
    <form class="site-form-register" action="{% url 'accounts:register' %}" method="post">
      {% csrf_token %}
      {% for field in form %}
      <div class="fieldWrapper-register">
        {{ field.errors }}
        <span class="field-tags">{{ field.label_tag }}</span> {{ field }}
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
      </div>
      {% endfor %}
      <button class="btn-register-auth" type="submit"><span>Register</span></button>
    </form>
    <p class="footer">Created by 0701CODER</p>
  </div>
</section>
{% endblock %}

templates/about.html
{% extends 'base_layout.html' %}

{% block content %}

<head>
  <meta charset="utf-8">
  <title>About</title>
</head>

<body style="background-color: #d0eaf2; color: #1f4070;">
  <h1>Created by Gladwin David , Sanjay Karthi , Vishnupriya  </h1>

  <pre><span class="about-content" style="font-size: 18px;">
      Electronic Gadgets a website that uses webscraping code written in Python
      to compare the prices of electronic products across the India's leading online scrapping.

      To use the webscraper the SuperUser creates the product and gives it a
      Category and Name. In this same section the URL for each electronic product
      is then entered and stored into the database. Once the load-prices.py file
      is ran it will go through each URL in the database and scrape the prices
      from each webpage. Erroneous URLs/prices will be flagged in the terminal
      to the user.

      As of january 2024 this webscraper currently works for Flipkart, Amazon
      and Snapdeal.
    </span></pre>
</body>
{% endblock %}

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'banner-styles.css' %}">
  </head>
  <header>
    <div class="logo-image">
      <h1><a href="{% url 'home' %}"><img src="{% static 'images1.png'%}" alt="SuperMarkIt"/></a></h1>
    </div>
    <nav>
      <ul>
        {% if user.is_authenticated %}
          <li><a href="{% url 'products:categories' %}" class="tag-categories-base">Categories</a></li>
          <li><a href="{% url 'products:main' %}" class="tag-products-base">Products</a></li>
          <li><a href="{% url 'basket:basket' %}" class="tag-basket-base">Basket</a></li>
          <li>
            <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" name="btn-logout">Logout</button>
            </form>
          </li>
        {% else %}
          <li><a href="{% url 'accounts:login' %}" class="tag-login-base">Login</a></li>
          <li><a href="{% url 'accounts:register' %}" class="tag-register-base">Register</a></li>
        {% endif %}
      </ul>
    </nav>
  </header>
  <body>
    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>
  </body>
</html>

templates/homepage.html
{% extends 'base_layout.html' %}
{% load static %}

<!DOCTYPE html>
{% block content %}
  <head>
    <meta charset="utf-8">
    <title>Homepage</title>
    <link rel="stylesheet" href="{% static 'homepage-styles.css' %}">
  </head>
  <body>
    <section class="hero">
      <div class="site-description">
        <h2>Electronic Gadgets shopping with a difference!</h2>
        <p>A webscraper that compares the prices of your shopping basket across the India's largest scrapping.</p>
        <br>
        <a href="{% url 'about' %}" class="tag-about">Find Out More!</a>
      </div>
    </section>
    <span class="created-by"><p>Created by Saranya</p></span>
  </body>
{% endblock %}